package motivationcloud

var phrases = []string{
	// Focus
	"stay focused",
	"deep work mode",
	"one thing at a time",
	"in the flow",
	"flow state",
	"stay with it",
	"in the zone",
	"full attention",
	"mind on task",
	"laser focus",
	"just be here",
	"single-tasking",
	"present moment",
	"clarity",
	"gently does it",
	"deep dive",
	"immerse yourself",
	"easy does it",

	// Encouragement
	"you got this",
	"keep going",
	"almost there",
	"believe in yourself",
	"you're doing great",
	"one step at a time",
	"trust the process",
	"stay the course",
	"looking good",
	"nice work",
	"well done so far",
	"keep it up",
	"way to go",
	"fantastic effort",
	"stellar work",
	"bravo",
	"nailing it",
	"on point",
	"superb",
	"outstanding",
	"remarkable",
	"impressive",
	"excellent",

	// Progress
	"progress not perfection",
	"small steps count",
	"every bit matters",
	"brick by brick",
	"inch by inch",
	"building momentum",
	"gaining ground",
	"moving forward",
	"step by step",
	"steady progress",
	"compound growth",
	"the work adds up",
	"seeds planted",
	"foundations laid",
	"getting closer",
	"on track",
	"making headway",
	"chipping away",
	"piece by piece",
	"level up",
	"growth in progress",
	"evolving",
	"improving daily",
	"bit by bit",
	"accumulating wins",

	// Energy
	"let's go",
	"good energy",
	"feeling it",
	"fresh start",
	"here we go",
	"warming up",
	"getting cozy",
	"spark of joy",

	// Mindset
	"growth mindset",
	"learn and adapt",
	"stay curious",
	"be kind to yourself",
	"good enough is great",
	"enjoy the process",
	"explore freely",
	"open mind",
	"keep learning",
	"embrace mistakes",
	"wonder",
	"elevate",

	// Calm & Steady
	"breathe",
	"stay calm",
	"patience pays off",
	"slow and steady",
	"trust yourself",
	"peace of mind",
	"balance",
	"ease into it",
	"find your rhythm",
	"gentle progress",
	"no rush",
	"smooth sailing",
	"take it easy",
	"at your own pace",
	"composed",
	"centered",
	"grounded",
	"serene focus",
	"quiet power",
	"inner strength",
	"stillness",
	"harmony",
	"equilibrium",
	"steady hands",
	"cool and collected",

	// Fun & Playful
	"enjoy the moment",
	"enjoy the ride",
	"have fun with it",
	"smile and code",
	"caffeinated focus",
	"happy coding",
	"shipping it",
	"ctrl+win",
	"deploy happiness",
	"bugs fear you",
	"code ninja",
	"syntax master",
	"pixel perfect",
	"chef's kiss",
	"smooth operator",
	"wizard mode",
	"magic happening",
	"legendary",
	"epic session",
	"glorious",
	"magnificent",
	"rad",
	"totally awesome",
	"vibes on point",
	"the best is now",
}
