package motivationcloud

var phrases = []string{
	// Focus
	"stay focused",
	"deep work mode",
	"one thing at a time",
	"lock in",
	"eyes on the prize",
	"zero distractions",
	"flow state",
	"tunnel vision",
	"stay sharp",
	"concentrate",
	"in the zone",
	"full attention",
	"mind on task",
	"laser focus",
	"block out the noise",
	"single-tasking",
	"present moment",
	"clarity",
	"sharpen the saw",
	"heads down",
	"deep dive",
	"immerse yourself",
	"total focus",
	"all in",
	"zone in",

	// Encouragement
	"you got this",
	"keep going",
	"almost there",
	"don't stop now",
	"believe in yourself",
	"you're doing great",
	"one step at a time",
	"trust the process",
	"stay the course",
	"keep pushing",
	"you're on fire",
	"crushing it",
	"nice work",
	"well done so far",
	"keep it up",
	"way to go",
	"fantastic effort",
	"stellar work",
	"bravo",
	"nailing it",
	"on point",
	"superb",
	"outstanding",
	"remarkable",
	"impressive",
	"excellent",

	// Progress
	"progress not perfection",
	"small steps count",
	"every bit matters",
	"brick by brick",
	"inch by inch",
	"building momentum",
	"gaining ground",
	"moving forward",
	"step by step",
	"steady progress",
	"compound growth",
	"the work adds up",
	"seeds planted",
	"foundations laid",
	"getting closer",
	"on track",
	"making headway",
	"chipping away",
	"piece by piece",
	"level up",
	"growth in progress",
	"evolving",
	"improving daily",
	"bit by bit",
	"accumulating wins",

	// Energy
	"let's go",
	"full steam ahead",
	"fire it up",
	"bring the energy",
	"power through",
	"unstoppable",
	"charge ahead",
	"ignite",
	"electrify",
	"amp it up",
	"go go go",
	"turbo mode",
	"maximum effort",
	"pedal to the metal",
	"all engines running",
	"full throttle",
	"blast off",
	"high gear",
	"no brakes",
	"rocket fuel",
	"energy surge",
	"beast mode",
	"fired up",
	"light it up",
	"boom",

	// Mindset
	"embrace the challenge",
	"growth mindset",
	"learn and adapt",
	"stay curious",
	"think big",
	"be bold",
	"dare greatly",
	"choose courage",
	"own it",
	"no excuses",
	"make it happen",
	"rise above",
	"be relentless",
	"stay hungry",
	"push boundaries",
	"defy limits",
	"break through",
	"aim higher",
	"dream big",
	"never settle",
	"raise the bar",
	"go beyond",
	"transcend",
	"elevate",
	"transform",

	// Calm & Steady
	"breathe",
	"stay calm",
	"patience pays off",
	"slow and steady",
	"trust yourself",
	"peace of mind",
	"balance",
	"ease into it",
	"find your rhythm",
	"gentle progress",
	"no rush",
	"smooth sailing",
	"take it easy",
	"grace under pressure",
	"composed",
	"centered",
	"grounded",
	"serene focus",
	"quiet power",
	"inner strength",
	"stillness",
	"harmony",
	"equilibrium",
	"steady hands",
	"cool and collected",

	// Fun & Playful
	"work hard play hard",
	"enjoy the ride",
	"have fun with it",
	"smile and code",
	"caffeinated focus",
	"keyboard warrior",
	"shipping it",
	"ctrl+win",
	"deploy happiness",
	"bugs fear you",
	"code ninja",
	"syntax master",
	"pixel perfect",
	"chef's kiss",
	"smooth operator",
	"wizard mode",
	"magic happening",
	"legendary",
	"epic session",
	"glorious",
	"magnificent",
	"rad",
	"totally awesome",
	"vibes on point",
	"the best is now",
}
